# used for segmentation
BACKGROUND_FLAG=0
BUILDING_FLAG=1
PEDESTRIAN_FLAG=4
POLES_FLAG=5
LANE_FLAG=6
ROAD_FLAG=7
SIDEWALK_FALG=8
VEHICLE_FLAG=10
# defined in yolo model
PEDESTRIAN_CLS=0
BICYCLE_CLS=1
CAR_CLS=2
MOTORBIKE_CLS=3
AEROPLANE_CLS=4
BUS_CLS=5
TRAIN_CLS=6
TRUCK_CLS=7
BOAT_CLS=8
TRAFFIC_CLS=9
